import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const envPath = resolve(root, '.env');
const outputPath = resolve(root, 'src/environments/environment.local.ts');

function parseEnvFile(content) {
  const values = {};

  for (const line of content.split('\n')) {
    const trimmed = line.trim();

    if (!trimmed || trimmed.startsWith('#')) {
      continue;
    }

    const separatorIndex = trimmed.indexOf('=');

    if (separatorIndex === -1) {
      continue;
    }

    const key = trimmed.slice(0, separatorIndex).trim();
    let value = trimmed.slice(separatorIndex + 1).trim();

    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }

    values[key] = value;
  }

  return values;
}

function readLicenseKey() {
  if (process.env.NG_APP_PRIMEUI_LICENSE_KEY) {
    return process.env.NG_APP_PRIMEUI_LICENSE_KEY;
  }

  if (!existsSync(envPath)) {
    return '';
  }

  const envValues = parseEnvFile(readFileSync(envPath, 'utf8'));
  return envValues.NG_APP_PRIMEUI_LICENSE_KEY ?? '';
}

const licenseKey = readLicenseKey();

writeFileSync(
  outputPath,
  `// Generated by scripts/sync-env.mjs. Do not edit manually.\nexport const localEnvironment = {\n  primeuiLicenseKey: ${JSON.stringify(licenseKey)}\n};\n`,
  'utf8'
);

console.log(`Wrote ${outputPath}`);
